### ISSUE TITLE
Support / Kein Taster/keine Temperatur - Minimallayout

### ISSUE THREAD

**Issue by JoeRu** [Honey-Pi/honeypi-pcb#1]
Hi,
ich weiß nicht ob das der "richtige" Weg f. eine Support-Anfrage ist - wenn nicht - einfach das Ticket schließen:

Ich bräuchte mal  etwas support; Ich habe im Dezember einen Set Platinen bestellt und versuche gerade ein minimal-Layout (Groove-Taster und Temp-Sensor) und bekomme aber keine Daten vom Taster und den Temperatur-Sensoren (Strom ist da);

[Hier ein Photo vom aktuellen Zustand](https://photos.app.goo.gl/vddKfQMpS9r4rim36)

Ich bin nicht ganz sicher - welche Bauteile noch minimal "da" sein müssen - damit Taster und Sensor funktionieren. 
Kontakt gern auch per Messenger.
Gruß
Johannes

**Comment by HeinKlocktein** [comment]
Hallo Johannes, 
Entschuldige die späte Antwort. Ich nutze diesen Teil nur zur Verteilung und habe entsprechend nicht bemerkt das Du...
Bist Du weitergekommen?
Im Ordner liegt ein Schaltplan als PDF. Schau Dir den mal an. 

Gruß

Michael
